component_depth: 1

languages:
  - name: cpp
    production:
      include:
        - /src/.*\.c
      exclude:
        - /src/parser\.c
        - /src/lexer\.c
        - /include/parser\.h
        - /include/lexer\.h
    test:
      include:
        - /tests/.*\.c
        - /tests/.*\.h
