component_depth: 1

languages:
  - name: cpp
    production:
      include:
        - /src/.*\.c
      exclude:
        - /windows_missing/.*\.c
    test:
      include:
        - /tests/.*\.c
        - /tests/.*\.h
