component_depth: 1

languages:
  - name: cpp
    production:
      include:
        - /src/.*\.c
      exclude:
        - /src/parser\.c
        - /src/lexer\.c
    test:
      include:
        - /tests/.*\.c
        - /tests/.*\.h

  - name: go
    production:
      include:
        - fake_entry
      exclude:
        - m4/.*m4
