language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
  allow_failures:
  - os: windows

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8

before_script:
  if [ $(uname) = "Linux" ];
  then if [ "$CC" = "gcc" ];
     then export CC=gcc-8;
     fi;
  elif [ $(uname) = "Darwin" ];
  then brew update;
  else
    export CFLAGS=-DBUILD_ON_WINDOWS;
    choco install make;
    alias gcc=gcc.exe;
    export CC="gcc.exe";
    alias make=make.exe;
    curl -L  http://downloads.sourceforge.net/project/gnuwin32/libgw32c/0.4/libgw32c-0.4-lib.zip > libgw32c.zip;
    tar xvf libgw32c.zip -C libgw32c ;
    CFLAGS=$CFLAGS -Ilibgw32c/include
    fi

script: 
  - if [ $(uname) = "Linux" ] || [ $(uname) = "Darwin" ];
    then make;
    else BUILD_ON_WINDOWS=1 make.exe;
    fi

