language: c

env:
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

os:
  - linux:
  - osx
  - windows

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8

compiler:
  - gcc
  - clang

script: make
