language: c

os:
  - linux
  - osx
  - windows

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8

compiler:
  - gcc
  - clang

install: if[ "$CC" = "gcc"] exprot CC=gcc-8
script: make
