language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

before_script:
  - export CICFLAGS="-Wno-attributes -Wno-unknown-pragmas";
  - if [ $(uname) = "Darwin" ];
    then brew update;
    elif [ $(uname) != "Linux" ];
      export CFLAGS=-DBUILD_ON_WINDOWS;
      choco install make;
      alias gcc=gcc.exe;
      export CC="gcc.exe";
    fi

script: 
  - if [ $(uname) = "Linux" ] || [ $(uname) = "Darwin" ];
    then make;
    else BUILD_ON_WINDOWS=1 make.exe;
    fi

