language: c


os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8

env:
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  - MATRIX_EVAL="TRAVIS_COMPILER==gcc-8"

script: make
