language: c

os:
  - linux
  - osx
  - windows

before_script:
  - export CICFLAGS="-Wno-attributes -Wno-unknown-pragmas";
  - if [ $(uname) = "Darwin" ];
    then brew update;
    elif [ $(uname) != "Linux" ]; then
      export BUILD_ON_WINDOWS;
      choco install make;
      export CC="gcc.exe";
    fi

script: 
  - if [ $(uname) = "Linux" ] || [ $(uname) = "Darwin" ];
    then make;
    else make.exe;
    fi

