matrix:
  fast_finish: true
  allow_failures:
  - os: osx

language: c


os:
  - linux
  - osc

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8

before_script:
  - if [ $(uname) = "linux" ]; if [ "$CC" = "gcc" ]; then export CC=gcc-8; fi; fi
  - if [ $(uname) != Linux ]; then brew update; fi

script: make
