name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }} ${{ matrix.cc }} ${{ matrix.double }}
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
      cc: [gcc, clang]
      double: [0, 1]
      
  steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: make test
      run: make test
