name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: {{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, window-latest]
        cc: [gcc, clang]
    steps:
    - uses: actions/checkout@v1
    - name: make CC=${{ matrix.cc }}
      run: make
