name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name:  ${{ matrix.os }} ${{ matrix.cc }} ${{ matrix.double && 'double' || '' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cc: [gcc, clang]
        double: [0, 1]
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: | 
        if [ ${{ matrix.os }} = windows-latest ];
        then export CFLAGS=-D${{ matrix.build }};
        fi
        make CC=${{ matrix.cc }}
