name: C/C++ CI

on: [push]

jobs:
  build:
  - name: ${{ matrix.os }} ${{ matrix.cc }} ${{ matrix.double && 'double' || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cc: [gcc, clang]
        double: [0, 1]
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: make CC=${{ matrix.cc }}
