name: C/C++ CI

on: [push]

jobs:
  build:
    matrix:
      os: [ ubuntu-latest, macos-latest, windows-latest ]
      cc: [ gcc, clang ]
      double: [ 0, 1]
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: make test
      run: make test
