name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name:  Linux ${{ matrix.cc }} ${{ matrix.double && 'double' || '' }}
    strategy:
      matrix:
        cc: [gcc, clang]
        double: [0, 1]
    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        USE_DOUBLE: ${{ matrix.double }}
      run: | 
        make CC=${{ matrix.cc }}
