name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name:  Linux ${{ matrix.cc }} ${{ matrix.double && 'double' || 'float '}}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      USE_DOUBLE: ${{ matrix.double }}
      CC: ${{ matrix.cc }}
    strategy:
      matrix:
        cc: [gcc, clang]
        double: [0, 1]
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule update --init
        make
