name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    #name:  ${{ matrix.cc }} ${{ matrix.double && 'double' || '' }}
    name:  ${{ matrix.double && 'double' || '' }}
    strategy:
      matrix:
#        cc: [gcc, clang]
        double: [0, 1]
    steps:
    - uses: actions/checkout@v1
    - name: check
      run: which cc; which gcc
    - name: build
      run: | 
        make CC=/c/ProgramData/Chocolatey/bin/gcc
#        make CC=${{ matrix.cc }}
