name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    name:  Windows ${{ matrix.double && 'double' || '' }}
    strategy:
      matrix:
        double: [0, 1]
    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        CFLAGS: -DBUILD_ON_WINDOWS
      run: | 
        make CC=$(which gcc) USE_DOUBLE=${{ matrix.double }}
#        make CC=/c/ProgramData/Chocolatey/bin/gcc
