name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    name:  Windows ${{ matrix.double && 'double' || 'float '}}
    strategy:
      matrix:
        double: [0, 1]
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: make
      env:
        BUILD_ON_WINDOWS: 1
        CC: gcc
        USE_DOUBLE: ${{ matrix.double }}
        BUILD_ON_WINDOWS: 1
